### ISSUE TITLE
ClassCastException bei Commands

### ISSUE THREAD

**Issue by EsGibtKeineMitte** [Butzlabben/worldsystem#24]
Hi Butzlabben,

seit der neusten BungeeCord Version(Ich glaube zumindestens, dass der Bug erst danach aufgetreten ist), kann ich keine Befehle mehr ausführen.

Hier die Exception:

[18:11:43 ERROR]: null
org.bukkit.command.CommandException: Unhandled exception executing 'ws tp' in net.myplayplanet.commandframework.internal.command.BukkitCommand(ws)
	at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:161) ~[patched_1.12.2.jar:git-Paper-1596]
	at org.bukkit.craftbukkit.v1_12_R1.CraftServer.dispatchCommand(CraftServer.java:685) ~[patched_1.12.2.jar:git-Paper-1596]
	at net.minecraft.server.v1_12_R1.PlayerConnection.handleCommand(PlayerConnection.java:1478) ~[patched_1.12.2.jar:git-Paper-1596]
	at net.minecraft.server.v1_12_R1.PlayerConnection.a(PlayerConnection.java:1283) ~[patched_1.12.2.jar:git-Paper-1596]
	at net.minecraft.server.v1_12_R1.PacketPlayInChat.a(PacketPlayInChat.java:45) ~[patched_1.12.2.jar:git-Paper-1596]
	at net.minecraft.server.v1_12_R1.PacketPlayInChat.a(PacketPlayInChat.java:5) ~[patched_1.12.2.jar:git-Paper-1596]
	at net.minecraft.server.v1_12_R1.PlayerConnectionUtils.lambda$ensureMainThread$0(PlayerConnectionUtils.java:14) ~[patched_1.12.2.jar:git-Paper-1596]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) ~[?:1.8.0_201]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) ~[?:1.8.0_201]
	at net.minecraft.server.v1_12_R1.SystemUtils.a(SourceFile:46) ~[patched_1.12.2.jar:git-Paper-1596]
	at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:850) ~[patched_1.12.2.jar:git-Paper-1596]
	at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:423) ~[patched_1.12.2.jar:git-Paper-1596]
	at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:774) ~[patched_1.12.2.jar:git-Paper-1596]
	at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:666) ~[patched_1.12.2.jar:git-Paper-1596]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_201]
Caused by: java.lang.ClassCastException: org.bukkit.craftbukkit.v1_12_R1.entity.CraftPlayer cannot be cast to net.md_5.bungee.api.CommandSender
	at net.myplayplanet.commandframework.CommandArgs.<init>(CommandArgs.java:19) ~[?:?]
	at net.myplayplanet.commandframework.internal.command.BukkitCommand.execute(BukkitCommand.java:60) ~[?:?]
	at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:151) ~[patched_1.12.2.jar:git-Paper-1596]
	... 14 more

Dies geschieht meines Wissens nach der neusten Bungee Version, auf einem Paperspigot Unterserver, wobei Paperspigot ansich nie Probleme gemacht hat.

Ich hoffe, ich konnte mit diesem Bugreport hilfreich sein.

MfG 
EsGibtKeineMitte | Leonhard

**Comment by Butzlabben** [comment]
Bei nur Paperspigot, ohne Bungee, selbe Exception?

**Comment by EsGibtKeineMItte** [comment]
Jep, ich denke, es wird an der neuen BungeeCord Version liegen.

**Comment by Butzlabben** [comment]
Should be fixed.
