### ISSUE TITLE
Error on /ws get

### ISSUE THREAD

**Issue by Pyario** [Butzlabben/worldsystem#36]
When i Enter /ws get become i this error:

`[14:22:35 WARN]: [WorldSystem] Task #5252 for WorldSystem v2.4.7.1 generated an exception
java.lang.NoClassDefFoundError: com/boydti/fawe/util/TaskManager
        at de.butzlabben.world.wrapper.AsyncCreatorAdapter.create(AsyncCreatorAdapter.java:21) ~[?:?]
        at de.butzlabben.world.wrapper.SystemWorld$1.run(SystemWorld.java:147) ~[?:?]
        at org.bukkit.craftbukkit.v1_14_R1.scheduler.CraftTask.run(CraftTask.java:84) ~[patched_1.14.4.jar:git-Paper-175]
        at org.bukkit.craftbukkit.v1_14_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:452) ~[patched_1.14.4.jar:git-Paper-175]
        at net.minecraft.server.v1_14_R1.MinecraftServer.b(MinecraftServer.java:1148) ~[patched_1.14.4.jar:git-Paper-175]
        at net.minecraft.server.v1_14_R1.DedicatedServer.b(DedicatedServer.java:417) ~[patched_1.14.4.jar:git-Paper-175]
        at net.minecraft.server.v1_14_R1.MinecraftServer.a(MinecraftServer.java:1075) ~[patched_1.14.4.jar:git-Paper-175]
        at net.minecraft.server.v1_14_R1.MinecraftServer.run(MinecraftServer.java:919) ~[patched_1.14.4.jar:git-Paper-175]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_221]
Caused by: java.lang.ClassNotFoundException: com.boydti.fawe.util.TaskManager
        at java.net.URLClassLoader.findClass(Unknown Source) ~[?:1.8.0_221]
        at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:139) ~[patched_1.14.4.jar:git-Paper-175]
        at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:85) ~[patched_1.14.4.jar:git-Paper-175]
        at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_221]
        at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_221]
        ... 9 more`

Spigot-Version: Paper-Spigot Build#175 - 1.14.4 :)
WorldSystem-Version: 2.4.7.1

**Comment by Pyario** [comment]
Hello?

**Comment by Butzlabben** [comment]
Which FAWE version are you using?

**Comment by Pyario** [comment]
Fawe is not stable/ready for 1.14.4. I use the normal WorldEdit.

**Comment by Butzlabben** [comment]
Pls show a screenshot of „/pl“

**Comment by Pyario** [comment]
Here: https://prnt.sc/p90njk

**Comment by Butzlabben** [comment]
As you can see, there is FAWE in your plugin list. That’s why WorldSystem thinks, it could use it. Is there a DummyFawe.jar?

**Comment by Pyario** [comment]
I use the normal Worldedit. Yes in the Plugin Folder is "DummyFawe.jar" :)

[10:56:08 INFO]: WorldEdit version (unknown)
[10:56:08 INFO]: https://github.com/EngineHub/worldedit/
[10:56:08 INFO]: ----------- Platforms -----------
[10:56:08 INFO]: * Bukkit-Official (7.0.1-SNAPSHOT;4593-df9d766)
[10:56:08 INFO]: ----------- Capabilities -----------
[10:56:08 INFO]: GAME_HOOKS: Bukkit-Official
[10:56:08 INFO]: CONFIGURATION: Bukkit-Official
[10:56:08 INFO]: USER_COMMANDS: Bukkit-Official
[10:56:08 INFO]: PERMISSIONS: Bukkit-Official
[10:56:08 INFO]: WORLDEDIT_CUI: Bukkit-Official
[10:56:08 INFO]: WORLD_EDITING: Bukkit-Official

**Comment by Pyario** [comment]
I've tested with the latest build of Fawe-Dev version seems to go with it + paperSpigot. No mistakes fast creation of the world. I think the problem is resolved.
